openapi: 3.0.0
info:
    title: SMS Gateway
    version: 0.0.1
    description: Arvancloud Challange
servers:
    - url: http://localhost:{port}
      description: Local development server
      variables:
          port:
              default: 3000

paths:
    /api/user/balance:
        post:
            summary: Create a user or update balance
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                balance:
                                    type: number
                            required:
                                - email
                                - balance
            responses:
                '200':
                    description: Balance applied
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                default: '2feff503-2bd3-41da-b0dd-b27101fd0031'
                                        required:
                                            - id
                '400':
                    $ref: '#/components/responses/ValidationFailed'

    /api/sms:
        post:
            summary: Send SMS
            parameters:
                - $ref: '#/components/parameters/Auth'
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                receiver_phone:
                                    type: string
                                content:
                                    type: string
                                is_express:
                                    type: boolean
                            required:
                                - receiver_phone
                                - content
                                - is_express
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        type: object
                                        properties:
                                            message_id:
                                                type: string
                                                default: '2feff503-2bd3-41da-b0dd-b27101fd0031'
                                            price:
                                                type: number
                                                default: 52.6
                                        required:
                                            - message_id
                                            - price
                '400':
                    $ref: '#/components/responses/ValidationFailed'
                '402':
                    description: Payment requiered

components:
    parameters:
        Auth:
            name: X-CLIENT-ID
            in: header
            description: User id
            required: true
            schema:
                type: string
    responses:
        ValidationFailed:
            description: Validation failed
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            errors:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        detail:
                                            type: string
                                            example: Validation error
